[package]
name = "tm4c129x-hal"
version = "0.8.0"
authors = [
	"Jorge Aparicio <jorge@japaric.io>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
	"Marc Poulhi√®s <dkm@kataplop.net>",
	"David Wood <code@dtwood.co.uk>",
]
description = "HAL for the TM4C129x family of microcontrollers"
keywords = ["arm", "cortex-m", "tm4c", "hal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/thejpster/tm4c-hal/tm4c129x-hal"
edition = "2018"

[dependencies]
cortex-m = "0.5"
nb = "0.1"
tm4c129x = "0.7"

[dependencies.cast]
version = "0.2"
default-features = false

[dependencies.embedded-hal]
version = "0.2"
features = ["unproven"]

[dependencies.void]
version = "1.0"
default-features = false

[dependencies.tm4c-hal]
# path = "../tm4c-hal"
version = "0.2.0"

[features]
rt = ["tm4c129x/rt"]
